// Package envfile handles writing secrets to .env files
package envfile

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Writer handles writing secrets to .env files
type Writer struct {
	filePath string
}

// NewWriter creates a new Writer for the specified file path
func NewWriter(filePath string) *Writer {
	return &Writer{
		filePath: filePath,
	}
}

// Write writes the secrets map to the .env file
// Keys are sorted alphabetically for consistent output
func (w *Writer) Write(secrets map[string]string) error {
	// Create directory if it doesn't exist
	dir := filepath.Dir(w.filePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	// Sort keys for consistent output
	keys := make([]string, 0, len(secrets))
	for key := range secrets {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	// Build content
	var builder strings.Builder
	builder.WriteString("# Generated by vaultpull\n")
	builder.WriteString("# Do not edit manually\n\n")

	for _, key := range keys {
		value := secrets[key]
		// Escape quotes and newlines in values
		value = strings.ReplaceAll(value, "\\", "\\\\")
		value = strings.ReplaceAll(value, "\"", "\\\"")
		value = strings.ReplaceAll(value, "\n", "\\n")
		
		builder.WriteString(fmt.Sprintf("%s=\"%s\"\n", key, value))
	}

	// Write to file with restricted permissions
	if err := os.WriteFile(w.filePath, []byte(builder.String()), 0600); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	return nil
}

// Exists checks if the .env file already exists
func (w *Writer) Exists() bool {
	_, err := os.Stat(w.filePath)
	return err == nil
}
